### ISSUE TITLE
演示地址博客的性能不佳

### ISSUE THREAD

**Issue by kingdido999** [chanshiyucx/SPA-Blog#1]
博主不考虑优化一下博客页面的性能吗？帧数很低，有十分明显的卡顿和迟缓。建议利用浏览器开发者工具来进行优化。

**Comment by chanshiyucx** [comment]
@kingdido999 
主要是鼠标点击特效造成卡帧，去掉特效的话就好很多了， 嘛~ 很多人都反映这个问题了~
